#!/bin/sh
tar cvvf ~/Sauv/sauv-poly-git.tar ./*.tex
tar rvvf ~/Sauv/sauv-poly-git.tar ./*.sty
tar rvvf ~/Sauv/sauv-poly-git.tar ./**/*.tex
tar rvvf ~/Sauv/sauv-poly-git.tar ./**/**/*.tex
tar rvvf ~/Sauv/sauv-poly-git.tar ./*.txt
tar rvvf ~/Sauv/sauv-poly-git.tar ./**/*.txt
tar rvvf ~/Sauv/sauv-poly-git.tar ./**/**/*.txt
tar rvvf ~/Sauv/sauv-poly-git.tar ./**/**/*.py
tar rvvf ~/Sauv/sauv-poly-git.tar ./**/**/*.sage
tar rvvf ~/Sauv/sauv-poly-git.tar ./**/**/*.png
tar rvvf ~/Sauv/sauv-poly-git.tar ./**/**/*.jpg
tar rvvf ~/Sauv/sauv-poly-git.tar ./**/**/*.tikz
gzip -f ~/Sauv/sauv-poly-git.tar
